import pandas as pd
import json
import mysql.connector
from flask import Flask, request, jsonify
from flask_cors import CORS

# -----------------------------------------------------------
# 1. FLASK APPLICATION SETUP
# -----------------------------------------------------------

app = Flask(__name__)
# Allows all front-end origins to connect for development purposes
CORS(app) 

# -----------------------------------------------------------
# 2. DATABASE CONFIGURATION (CRITICAL STEP)
#    !!!! UPDATE THESE VALUES WITH YOUR ACTUAL MYSQL DETAILS !!!!
# -----------------------------------------------------------

DB_CONFIG = {
    "host": "localhost",
    "user": "root", 
    "password": "",  # <-- MUST BE UPDATED
    "database": ""                # <-- MUST be the schema name (sakila)
}													

# FIX APPLIED HERE: Using 'etl_data' to match your MySQL Workbench screenshot
TARGET_TABLE = "etl_data" 

# -----------------------------------------------------------
# 3. LOAD ENDPOINT LOGIC
# -----------------------------------------------------------

@app.route('/api/load', methods=['POST'])
def load_data():
    """Receives transformed JSON data and loads it into MySQL."""
    
    if not request.json:
        return jsonify({"status": "error", "message": "No JSON data received from front-end."}), 400

    transformed_records = request.json
    db_connection = None
    
    # Columns MUST match the column names generated by your Pandas transformation
    # and the columns defined in your MySQL CREATE TABLE statement (for 'etl_data').
    expected_columns = [
        'user_id', 'course_id', 'discount_offer', 'course_name',
        'price_before_discount', 'user_name', 'country', 'price_after_discount'
    ]

    try:
        # 1. Connect to MySQL
        db_connection = mysql.connector.connect(**DB_CONFIG)
        cursor = db_connection.cursor()

        # 2. Define the parameterized INSERT SQL QUERY
        columns_str = ", ".join(expected_columns)
        placeholders = ", ".join(["%s"] * len(expected_columns))
        
        # This is the SQL command structure
        sql_insert_query = f"INSERT INTO {TARGET_TABLE} ({columns_str}) VALUES ({placeholders})"
        
        # 3. Prepare data for batch execution
        data_to_insert = []
        for record in transformed_records:
            # Map the JSON values to a tuple in the correct column order
            row_values = [record.get(col) for col in expected_columns]
            data_to_insert.append(tuple(row_values))

        # 4. EXECUTE the SQL QUERY using executemany for efficiency
        cursor.executemany(sql_insert_query, data_to_insert)
        db_connection.commit() # Commit the changes to the database
        
        # Return success message
        return jsonify({
            "status": "success", 
            "message": f"Successfully loaded {cursor.rowcount} records into the '{TARGET_TABLE}' table."
        }), 200

    except mysql.connector.Error as err:
        # Note: If the table structure is wrong, you'll get a different error (e.g., column count mismatch).
        print(f"Database Error: {err}")
        return jsonify({
            "status": "error", 
            "message": f"MySQL Database Error. Please verify DB_CONFIG and table schema. Error: {err}"
        }), 500

    except Exception as e:
        print(f"An unexpected server error occurred: {e}")
        return jsonify({
            "status": "error", 
            "message": f"An unexpected server error occurred: {e}"
        }), 500

    finally:
        # Always close the connection
        if db_connection and db_connection.is_connected():
            db_connection.close()
            print("MySQL connection closed.")

if __name__ == '__main__':
    print("Starting Flask app on http://localhost:5000...")
    # Run the server. Use 127.0.0.1 (or localhost) to match the front-end URL
    app.run(host='127.0.0.1', port=5000, debug=True)
